### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by betogulliver** [cptanalatriste/aco-set-covering#1]
when I try to run your program I got the error below. Any ideas on how I can make it run w/o errors?

thanks for your great work!

% mvn exec:java -Dexec.mainClass="setcov.isula.sample.AcoSetCoveringWithIsula" -D exec.args="-f ./data/AC_10_cover.txt"
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< isula:aco-set-covering >-----------------------
[INFO] Building aco-set-covering 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec:3.3.0:java (default-cli) @ aco-set-covering ---
[WARNING] 
java.lang.ClassNotFoundException: setcov.isula.sample.AcoSetCoveringWithIsula
    at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass (URLClassLoaderBuilder.java:181)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:526)
    at org.codehaus.mojo.exec.ExecJavaMojo.doExec (ExecJavaMojo.java:371)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:296)
    at java.lang.Thread.run (Thread.java:1583)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.193 s
[INFO] Finished at: 2024-06-01T22:15:45+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.3.0:java (default-cli) on project aco-set-covering: An exception occurred while executing the Java class. setcov.isula.sample.AcoSetCoveringWithIsula -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
%

**Comment by cptanalatriste** [comment]
Hi @betogulliver , thanks for your interest in the project. I'm not able to replicate the issue on my side: The command works as long as you have Java and Maven installed.

Are you running `mvn` from the root directory of the project? It appears it's not locating the `AcoSetCoveringWithIsula` class file?

**Comment by betogulliver** [comment]
Hi @cptanalatriste , thanks for your propmt reply. Much appreciated.

Yes, I'm runing the command from the project root directory
     ~/projects/aco-set-covering

the AcoSetCoveringWithIsula class file is here but somehow is not found(?):
    ./src/main/java/setcov/isula/sample/AcoSetCoveringWithIsula.java


FYI, this is my enviro setup. Also the log of my runing with the 'mvn -X' option

% mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.22, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-107-generic", arch: "amd64", family: "unix"

% java --version
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu220.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu220.04.1, mixed mode, sharing)

% javac --version
javac 11.0.22
(iaml) r.lopez@jupiter%cd /tmp/


(iaml) r.lopez@jupiter% ls 
img/  LICENSE  pom.xml  problem_data/  README.md  src/
(iaml) r.lopez@jupiter% mvn -X exec:java -Dexec.mainClass="setcov.isula.sample.AcoSetCoveringWithIsula" -D exec.args="-f ./data/AC_10_cover.txt"
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.22, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-107-generic", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.annotation.* < plexus.core
[DEBUG]   Imported: javax.annotation.security.* < plexus.core
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.fusesource.jansi.* < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.event.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/r.lopez/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /home/r.lopez/.m2/toolchains.xml
[DEBUG] Using local repository at /home/r.lopez/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /home/r.lopez/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project isula:aco-set-covering:jar:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 3.3.0 from repository central (https://repo.maven.apache.org/maven2, default, releases)
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: isula:aco-set-covering:jar:1.0-SNAPSHOT
[DEBUG] Tasks:   [exec:java]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO] 
[INFO] -----------------------< isula:aco-set-covering >-----------------------
[INFO] Building aco-set-covering 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/r.lopez/.m2/repository)
[DEBUG] Skipped remote request for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 3.3.0 from repository central (https://repo.maven.apache.org/maven2, default, releases)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       isula:aco-set-covering:1.0-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [isula (https://packagecloud.io/cgavidia/isula/maven2, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:3.3.0:java (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <addOutputToClasspath default-value="true">${addOutputToClasspath}</addOutputToClasspath>
  <addResourcesToClasspath default-value="false">${addResourcesToClasspath}</addResourcesToClasspath>
  <arguments>${exec.arguments}</arguments>
  <blockSystemExit default-value="false">${exec.blockSystemExit}</blockSystemExit>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <cleanupDaemonThreads default-value="true">${exec.cleanupDaemonThreads}</cleanupDaemonThreads>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <daemonThreadJoinTimeout default-value="15000">${exec.daemonThreadJoinTimeout}</daemonThreadJoinTimeout>
  <includePluginDependencies default-value="false">${exec.includePluginsDependencies}</includePluginDependencies>
  <includeProjectDependencies default-value="true">${exec.includeProjectDependencies}</includeProjectDependencies>
  <keepAlive default-value="false">${exec.keepAlive}</keepAlive>
  <mainClass>${exec.mainClass}</mainClass>
  <pluginDependencies default-value="${plugin.artifacts}"/>
  <preloadCommonPool default-value="0">${exec.preloadCommonPool}</preloadCommonPool>
  <project default-value="${project}"/>
  <session default-value="${session}"/>
  <skip default-value="false">${exec.skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <stopUnresponsiveDaemonThreads default-value="false">${exec.stopUnresponsiveDaemonThreads}</stopUnresponsiveDaemonThreads>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
</configuration>
[DEBUG] =======================================================================
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=630179, ConflictMarker.markTime=142130, ConflictMarker.nodeCount=21, ConflictIdSorter.graphTime=348266, ConflictIdSorter.topsortTime=283328, ConflictIdSorter.conflictIdCount=11, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2931101, ConflictResolver.conflictItemCount=20, DefaultDependencyCollector.collectTime=41907451, DefaultDependencyCollector.transformTime=6096202}
[DEBUG] isula:aco-set-covering:jar:1.0-SNAPSHOT
[DEBUG]    isula:isula:jar:2.0.1:compile
[DEBUG]       org.apache.commons:commons-lang3:jar:3.0:compile
[DEBUG]    org.junit.jupiter:junit-jupiter:jar:5.6.0:test
[DEBUG]       org.junit.jupiter:junit-jupiter-api:jar:5.6.0:test
[DEBUG]          org.apiguardian:apiguardian-api:jar:1.1.0:test
[DEBUG]          org.opentest4j:opentest4j:jar:1.2.0:test
[DEBUG]          org.junit.platform:junit-platform-commons:jar:1.6.0:test
[DEBUG]       org.junit.jupiter:junit-jupiter-params:jar:5.6.0:test
[DEBUG]       org.junit.jupiter:junit-jupiter-engine:jar:5.6.0:test
[DEBUG]          org.junit.platform:junit-platform-engine:jar:1.6.0:test
[DEBUG]    org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] 
[INFO] --- exec-maven-plugin:3.3.0:java (default-cli) @ aco-set-covering ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=67436, ConflictMarker.markTime=80219, ConflictMarker.nodeCount=11, ConflictIdSorter.graphTime=19058, ConflictIdSorter.topsortTime=16009, ConflictIdSorter.conflictIdCount=9, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=360070, ConflictResolver.conflictItemCount=11, DefaultDependencyCollector.collectTime=47541180, DefaultDependencyCollector.transformTime=610511}
[DEBUG] org.codehaus.mojo:exec-maven-plugin:jar:3.3.0
[DEBUG]    org.apache.maven.resolver:maven-resolver-util:jar:1.4.1:compile
[DEBUG]       org.apache.maven.resolver:maven-resolver-api:jar:1.4.1:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:4.0.1:compile
[DEBUG]    org.codehaus.plexus:plexus-xml:jar:3.0.0:compile
[DEBUG]    org.apache.commons:commons-exec:jar:1.4.0:compile
[DEBUG]    org.ow2.asm:asm:jar:9.7:compile
[DEBUG]    org.ow2.asm:asm-commons:jar:9.7:compile
[DEBUG]       org.ow2.asm:asm-tree:jar:9.7:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:exec-maven-plugin:3.3.0
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-maven-plugin:3.3.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:exec-maven-plugin:3.3.0
[DEBUG]   Included: org.codehaus.mojo:exec-maven-plugin:jar:3.3.0
[DEBUG]   Included: org.apache.maven.resolver:maven-resolver-util:jar:1.4.1
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:4.0.1
[DEBUG]   Included: org.codehaus.plexus:plexus-xml:jar:3.0.0
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.4.0
[DEBUG]   Included: org.ow2.asm:asm:jar:9.7
[DEBUG]   Included: org.ow2.asm:asm-commons:jar:9.7
[DEBUG]   Included: org.ow2.asm:asm-tree:jar:9.7
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:3.3.0:java from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:3.3.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@55054057]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:3.3.0:java' with basic configurator -->
[DEBUG]   (f) addOutputToClasspath = true
[DEBUG]   (f) addResourcesToClasspath = false
[DEBUG]   (f) arguments = []
[DEBUG]   (f) blockSystemExit = false
[DEBUG]   (f) classpathScope = runtime
[DEBUG]   (f) cleanupDaemonThreads = true
[DEBUG]   (f) commandlineArgs = -f ./data/AC_10_cover.txt
[DEBUG]   (f) daemonThreadJoinTimeout = 15000
[DEBUG]   (f) includePluginDependencies = false
[DEBUG]   (f) includeProjectDependencies = true
[DEBUG]   (f) keepAlive = false
[DEBUG]   (f) mainClass = setcov.isula.sample.AcoSetCoveringWithIsula
[DEBUG]   (f) pluginDependencies = [org.codehaus.mojo:exec-maven-plugin:maven-plugin:3.3.0:, org.apache.maven.resolver:maven-resolver-util:jar:1.4.1:compile, org.apache.maven.resolver:maven-resolver-api:jar:1.4.1:compile, org.codehaus.plexus:plexus-utils:jar:4.0.1:compile, org.codehaus.plexus:plexus-xml:jar:3.0.0:compile, org.apache.commons:commons-exec:jar:1.4.0:compile, org.ow2.asm:asm:jar:9.7:compile, org.ow2.asm:asm-commons:jar:9.7:compile, org.ow2.asm:asm-tree:jar:9.7:compile]
[DEBUG]   (f) preloadCommonPool = 0
[DEBUG]   (f) project = MavenProject: isula:aco-set-covering:1.0-SNAPSHOT @ /tmp/aco-set-covering/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@37095ded
[DEBUG]   (f) skip = false
[DEBUG]   (f) stopUnresponsiveDaemonThreads = false
[DEBUG] -- end configuration --
[DEBUG] Invoking : setcov.isula.sample.AcoSetCoveringWithIsula.main()
[DEBUG] Plugin Dependencies will be excluded.
[DEBUG] Project Dependencies will be included.
[DEBUG] Collected project artifacts [isula:isula:jar:2.0.1:compile, org.apache.commons:commons-lang3:jar:3.0:compile, org.apache.commons:commons-math3:jar:3.6.1:compile]
[DEBUG] Collected project classpath [/tmp/aco-set-covering/target/classes]
[DEBUG] Adding to classpath : /tmp/aco-set-covering/target/classes
[DEBUG] Adding project dependency artifact: isula to classpath
[DEBUG] Adding project dependency artifact: commons-lang3 to classpath
[DEBUG] Adding project dependency artifact: commons-math3 to classpath
[DEBUG] joining on thread Thread[setcov.isula.sample.AcoSetCoveringWithIsula.main(),5,setcov.isula.sample.AcoSetCoveringWithIsula]
[WARNING] 
java.lang.ClassNotFoundException: setcov.isula.sample.AcoSetCoveringWithIsula
    at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass (URLClassLoaderBuilder.java:181)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:527)
    at org.codehaus.mojo.exec.ExecJavaMojo.doExec (ExecJavaMojo.java:371)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:296)
    at java.lang.Thread.run (Thread.java:829)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.552 s
[INFO] Finished at: 2024-06-03T17:16:15+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.3.0:java (default-cli) on project aco-set-covering: An exception occurred while executing the Java class. setcov.isula.sample.AcoSetCoveringWithIsula -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.3.0:java (default-cli) on project aco-set-covering: An exception occurred while executing the Java class. setcov.isula.sample.AcoSetCoveringWithIsula
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occurred while executing the Java class. setcov.isula.sample.AcoSetCoveringWithIsula
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:363)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: setcov.isula.sample.AcoSetCoveringWithIsula
    at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass (URLClassLoaderBuilder.java:181)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:527)
    at org.codehaus.mojo.exec.ExecJavaMojo.doExec (ExecJavaMojo.java:371)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:296)
    at java.lang.Thread.run (Thread.java:829)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
%

**Comment by cptanalatriste** [comment]
It might be an issue with the `mvn:exec` task. Can you please do a pull (I just committed some changes) and run `mvn test` and `mvn install`?

**Comment by betogulliver** [comment]
now, I can run your code! thank you very much!
(see below for details)

BTW, I run into the same problem with some other projects of yours, maybe the same fix is in place for them too :)
 
https://github.com/cptanalatriste/aco-swe-gecco-tutorial
https://github.com/cptanalatriste/aco-tsp
https://github.com/cptanalatriste/aco-acs-tsp

this is what I did

git clone https://github.com/cptanalatriste/aco-set-covering
cd aco-set-covering
mvn test # passed
mvn install # passed
mvn exec:java -Dexec.mainClass="setcov.isula.sample.AcoSetCoveringWithIsula" -D exec.args="-f `./problem_data/AC_10_cover.txt"`
...
INFO: Best solution: 1224 80 1660 356 1461 1128 1894 1640 1470 1418 1030 898 1232 1756 1140 2006 2564 902 120 2002 1260 1496
...

**Comment by cptanalatriste** [comment]
I'm glad it is working now! I'm going to close this issue then, please let me know if you're still having problems with the other repos.
